<?php

/**
 * @file
 * Allow to override ting_details_subjects field.
 */

include "lib/SO.php";

use SO\SubjectsOverrides as SubjectsOverrides;

/**
 * Implements hook_entity_prepare_view().
 *
 * @throws \ReflectionException
 */
function ting_subjects_override_entity_prepare_view($entities, $type, $langcode) {
  if ($type == 'ting_object') {
    $entity = array_shift($entities);
    $call_class = new SubjectsOverrides($entity);

    // Instantiate the reflection object.
    $reflector = new ReflectionClass($call_class);

    // Now get all the properties from class A in to $properties array.
    $properties = $reflector->getProperties();

    // Now go through the $properties array and populate each property.
    foreach ($properties as $property) {
      // Invoking the method to print what was populated.
      if ($property->getName() == 'subjects') {
        $call_class->{"getSubjects"}();
      }
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ting_subjects_override_preprocess_field(&$variables) {
  $field_name = $variables["element"]["#field_name"];

  if ($field_name == 'ting_subjects') {
    $object = $variables['element']['#object'];

    if (!empty($object->subjects)) {
      $search_string = variable_get('ting_search_register_subject', 'phrase.subject="@subject"');
      $subject_links = array_map(function ($subject) use ($search_string) {
        $replacement = ['@subject' => $subject];
        $options = [
          'attributes' => ['class' => ['subject']],
        ];
        return ting_field_search_link($subject, $search_string, $replacement, $options);
      }, $object->subjects);

      $variables['items'][0]['#markup'] = implode(' ', $subject_links);
    }
  }
}

/**
 * Implements hook_ding_entity_view().
 */
function ting_subjects_override_ding_entity_view($object, $view_mode) {
  if (!empty($object->subjects)) {
    $field_instance = field_info_instance('ting_object', 'ting_subjects', 'ting_object');
    $display = ($view_mode === 'full') ? 'default' : $view_mode;

    if ($field_instance['display'][$display]['type'] === 'hidden') {
      return;
    }

    $options = [
      '#theme' => 'field',
      '#title' => t($field_instance['label']),
      '#weight' => $field_instance['display'][$display]['weight'],
      '#formatter' => $field_instance['display'][$display]['type'],
      '#bundle' => 'ting_object',
      '#entity_type' => 'ting_object',
      '#field_name' => 'ting_subjects',
      '#field_type' => 'ting_subjects',
      '#object' => $object,
      '#view_mode' => $view_mode,
      '#access' => TRUE,
    ];

    $object->content += [
      'ting_subjects' => $options,
    ];
  }
}
